### ISSUE TITLE
Unable to open 'apexsky.lib'

### ISSUE THREAD

**Issue by andylee10001** [TheWindWa1ker/FATE_APEX_DMACheat-WithKmBox-#3]
Unable to open 'apexsky.lib'
![螢幕擷取畫面 2024-09-17 114132](https://github.com/user-attachments/assets/d3f0294b-16a4-4626-b1ad-b79925abe2ca)

**Comment by TheWindWa1ker** [comment]
你需要先安裝rust庫，然後使用cargo build構建這個'apexsky.lib'，在apexsky文件夾裏面
